# Generated by Django 5.1.3 on 2024-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_img', models.ImageField(upload_to='product_image')),
                ('show', models.BooleanField(default=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
