# Generated by Django 5.1.3 on 2024-11-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
    ]
