# Generated by Django 5.1.3 on 2024-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
